{
 "title": "VM",
 "description": "Vitual Machine Metrics from Libvirt Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Hypervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Emulator Syscall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(ebpf_exporter_syscalls_per_cgroup{job=\"ebpf_exporter\", instance=\"worknode:9435\", cgroup=~\"/sys/fs/cgroup/machine.slice/machine-qemu\\\\\\\\x2d4\\\\\\\\x2d.*/emulator\"}[$__interval])) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "VCPU Syscall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(ebpf_exporter_syscalls_per_cgroup{job=\"ebpf_exporter\", instance=\"worknode:9435\", cgroup=~\"/sys/fs/cgroup/machine.slice/machine-qemu\\\\\\\\x2d4\\\\\\\\x2d.*/vcpu.*\"}[$__interval])) by (syscall)",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Time",
   "type": "timeseries",
   "description": "虚拟机的cpu使用时间",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "clamp_min(rate(libvirt_domain_cpu_time_sys{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval]), 0) / 1000",
     "legendFormat": "sys"
    },
    {
     "expr": "clamp_min(irate(libvirt_domain_cpu_time_user{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval]), 0) / 1000",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "VCPU Time Per Seconds",
   "type": "timeseries",
   "description": "vcpu线程的cpu使用时间",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_vcpu_time_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain) / 1000",
     "legendFormat": "vcpu"
    }
   ]
  },
  {
   "title": "Context Switch",
   "type": "timeseries",
   "description": "虚拟机级别的内核上下文切换次数",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "clamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"context_switch\"}[$__interval]) , 0)",
     "legendFormat": "context_switch"
    }
   ]
  },
  {
   "title": "Branch IPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"branch_instructions\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycle Per Instruction",
   "type": "timeseries",
   "description": "虚拟机的每指令周期数",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "clamp_min(delta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"cpu_cycles\"}[$__interval]), 0)\n/on(domain)\nclamp_min(delta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[$__interval]), 1)",
     "legendFormat": "cpi"
    }
   ]
  },
  {
   "title": "Instructions Per Second",
   "type": "timeseries",
   "description": "虚拟机每秒执行指令数",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "rate(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[$__interval])",
     "legendFormat": "ins"
    }
   ]
  },
  {
   "title": "Branch Miss Per Branch Instructions",
   "type": "timeseries",
   "description": "虚拟机每千条指令预测失败比例，用于应用特征分析",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "1000 * clamp_min(delta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\",instance=\"worknode:9177\", job=\"libvirt_exporter\",event=\"branch_misses\"}[$__interval]), 0)\r\n/on(domain)\r\nclamp_min(delta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"branch_instructions\"}[$__interval]), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Misses per Thousand Instructions",
   "type": "timeseries",
   "description": "每千条指令的cache命中缺失次数",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "1000 * clamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\",instance=\"worknode:9177\", job=\"libvirt_exporter\",event=\"cache_misses\"}[$__interval]), 0)\n/on(domain)\nclamp_min(idelta(libvirt_domain_perf_count{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\", event=\"instructions\"}[$__interval]), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last-Level Cache Capacity",
   "type": "timeseries",
   "description": "末级缓存容量",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 27 },
   "targets": [
    {
     "expr": "resctrl_llc_occupancy_bytes{group=\"podman-alpine317_default\", job=\"resctrl_exporter\", instance=\"worknode:9001\"} / 1024 / 28160",
     "legendFormat": "vm_occupancy_numa_{{numa}}"
    },
    {
     "expr": "resctrl_llc_occupancy_bytes{group=\"global\", job=\"resctrl_exporter\", instance=\"worknode:9001\"} / 1024 / 28160",
     "legendFormat": "total_occupancy_numa_{{numa}}"
    }
   ]
  },
  { "title": "Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Usage",
   "type": "timeseries",
   "description": "虚拟机内部内存利用率",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "100 * (libvirt_domain_memory_stats_available_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}\r\n - libvirt_domain_memory_stats_unused_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"})\r\n / libvirt_domain_memory_stats_actual_balloon_bytes{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth Local",
   "type": "timeseries",
   "description": "Local Bandwidth from Intel RDT, MBps",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "irate(resctrl_mem_bandwidth_local_bytes{group=\"podman-alpine317_default\", job=\"resctrl_exporter\", instance=\"worknode:9001\"}[$__interval]) / 1024 / 1024",
     "legendFormat": "local_numa_{{numa}}"
    },
    {
     "expr": "irate(resctrl_mem_bandwidth_total_bytes{group=\"podman-alpine317_default\", job=\"resctrl_exporter\", instance=\"worknode:9001\"}[$__interval]) / 1024 / 1024",
     "legendFormat": "total_numa_{{numa}}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Bytes",
   "type": "timeseries",
   "description": "网络接收和发送比特",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance) / 1024",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance) / 1024",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_receive_packets_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(libvirt_domain_interface_stats_transmit_packets_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance)",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "Block IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "bytes io",
   "type": "timeseries",
   "description": "每秒读写比特",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain)",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_bytes_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "description": "每秒读写请求数量",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_requests_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance, job)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_requests_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance, job)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "time",
   "type": "timeseries",
   "description": "读写耗时",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_block_stats_write_time_seconds_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance, job)",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(libvirt_domain_block_stats_read_time_seconds_total{domain=\"podman-alpine317_default\", instance=\"worknode:9177\", job=\"libvirt_exporter\"}[$__interval])) by(domain, instance, job)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "flush request and time",
   "type": "timeseries",
   "description": "当前内存刷新请求，反应内存cache情况",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_flush_requests_total{domain=\"podman-alpine317_default\",instance=\"worknode:9177\",job=\"libvirt_exporter\"}[$__interval])",
     "legendFormat": "request_{{target_device}}"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_flush_time_seconds_total{domain=\"podman-alpine317_default\",instance=\"worknode:9177\",job=\"libvirt_exporter\"}[$__interval])",
     "legendFormat": "time_{{target_device}}"
    }
   ]
  },
  {
   "title": "sector offset",
   "type": "timeseries",
   "description": "磁盘扇区偏移，可以知道最近是否有落盘动作和每次罗盘多少比特",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_allocation{domain=\"podman-alpine317_default\",instance=\"worknode:9177\",job=\"libvirt_exporter\"}",
     "legendFormat": "offset_{{target_device}}"
    }
   ]
  },
  {
   "title": "iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "libvirt_domain_block_stats_size_iops_bytes{domain=\"podman-alpine317_default\",instance=\"worknode:9177\",job=\"libvirt_exporter\"}",
     "legendFormat": "iops_{{target_device}}"
    }
   ]
  }
 ]
}